# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c9c167eaa8b20e925438926c76d0f97a0b81ec1dd80d0b73d28a5abb499e021343b0521ea8e2481f19ad9325fe28dd7834e29e4db40df861885eebbd003f2d5

test:
  secret_key_base: d3fcc4e137f48be30f233ca72c3e9366ff571f73603da469bbccbdedbdaea90832e1b109cd1b61b8de7d96362a5fc35fcf8cc1dd0f698db029b439686da01900

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
